### ISSUE TITLE
lpass mv disregards read-only permissions

### ISSUE THREAD

**Issue by TKonczynski** [lastpass/lastpass-cli#186] opened 2016-07-18 12:23 UTC
Hello,
I've been using lpass-cli for the past few days quite extensively and, due to a bug, I guess, accidentally moved a note from a shared catalogue to which I have read access only to a shared folder whose I'm the only owner.
How could this have happened?

**Comment by bcopeland** [comment] 2016-07-20 19:19
Can you give minimal steps to reproduce?

I tried the following:
 * userA is folder admin, userB has readonly
```
(as user A)
$ lpass share userls Shared-Folder1
User                                         RO  Admin   Hide OutEnt Accept
[userA]                                       _      x      _      _      x
[userB]                                        x      _      _      _      x

(as user B)
$ lpass mv Shared-Folder1/sharedsitex mydir
Error: Move to/from shared folder failed (-22)

(as user A)
$ lpass mv sharedsitex Shared-Folder2
(worked)
```

```

**Comment by bcopeland** [comment] 2016-08-17 20:37
Bump?

**Comment by bcopeland** [comment] 2016-09-16 20:03
Closing as unable to reproduce.

**Closed by bcopeland** 2016-09-16 20:03 UTC
