### ISSUE TITLE
lpass show keyname --field='Private Key' only ever shows first line of key

### ISSUE THREAD

**Issue by weeble** [lastpass/lastpass-cli#296] opened 2017-04-14 16:55 UTC
I have the same problem described in closed issue #275. I only ever get the first line of the private key out of lpass show. I've tried creating secure notes via the web UI and via the Chrome extension. (All on Chrome on Mac.) The results are like this:

```
$ lpass show another-test-key --all
another-test-key [id: 1377944694344055003]
Date: ,,
Hostname:
Public Key:
DEK-Info:  AES-128-CBC,5D74E06F722A5AD7F94392DBCBD42757
Proc-Type:  4,ENCRYPTED
Private Key: -----BEGIN RSA PRIVATE KEY-----
Passphrase:
Format:
Bit Strength:
NoteType: SSH Key
$ lpass show another-test-key --field='Private Key'
-----BEGIN RSA PRIVATE KEY-----
```

The whole private key is definitely stored by Lastpass, because I can copy it out of the field in the UI, even though it doesn't display very well (it's a multi-line field scrolling up and down in a tiny entry box).

Is there a way to get this out?

**Comment by slax0rr** [comment] 2017-04-25 18:43
Storing the private key from a `vim` editor as multi-line does not save the whole key, but just the `-----BEGIN RSA PRIVATE KEY-----` part.

**Comment by bcopeland** [comment] 2017-04-26 00:22
There are actually two separate but related issues here:

1) form fields in lastpass-cli have to be all on a single line.  You *can* save a private key, though, provided you join all the lines -- "lpass show" will then expand them properly.  I pushed a test case today demonstrating that and using `tr` to remove newlines.

2) The LastPass plugins support a new format for multiline fields, that lastpass-cli hasn't been updated to support (yet, working on it).  Because of this, if you paste a key into edit account in the plugin, you'll get back only the -----BEGIN PRIVATE KEY----- header.

**Comment by bcopeland** [comment] 2017-04-26 20:13
Can you try latest master, I just pushed some changes for this.

**Comment by weeble** [comment] 2017-05-01 11:50
Yes, that seems to work with the current master. I can do `lpass show another-test-key --field 'Private Key' and get the full contents of the private key field. I note that something weird is going on with the "Notes" field - for me it seems to have disappeared and instead appears as extra text appended to the end of the date field, but I'll need to investigate further.

**Comment by bcopeland** [comment] 2017-05-31 18:48
If you can give me steps to reproduce I'll take a look.

**Comment by bcopeland** [comment] 2017-06-07 16:47
I'm going to go ahead and close this, please report the notes-field mangling separately.

**Closed by bcopeland** 2017-06-07 16:47 UTC
