### ISSUE TITLE
lpass cli does not allow downloading of attached files from a secure note 

### ISSUE THREAD

**Issue by sidsarasvati** [lastpass/lastpass-cli#98] opened 2015-06-19 19:43 UTC
STR:
1. Create a secure note of type SSH Key
2. Attach public and private key file
3. use last pass cli to show this note
4. The files are not listed and moreover there is no way to download these files.

**Comment by bcopeland** [comment] 2015-08-06 21:08
yes this is a duplicate of #1 (but you can show key fields now).

**Closed by bcopeland** 2015-08-06 21:08 UTC
