### ISSUE TITLE
Interface is extremely slow - bug or feature?

### ISSUE THREAD

**Issue by whnr** [lastpass/lastpass-cli#475] opened 2019-02-21 14:30 UTC
Hi,

I find that the cli is very slow. Is that due to on demand decryption of information at each query? Here is a sample:

`lpass show --user mailbox.org  0,08s user 0,01s system 14% cpu 0,607 total`

That is 0,598s that are going somewhere… subsequent calls with the same command are fast (40ms) for about 1 to 5 seconds. Then there is a single slow query again.

* LastPass CLI v1.3.1
* Linux hostname 4.20.10-arch1-1-ARCH #1 SMP PREEMPT Fri Feb 15 17:49:06 UTC 2019 x86_64 GNU/Linux

--Florian

**Comment by waterkip** [comment] 2019-03-19 19:36
Do you have IPv6 enabled by any chance?

**Comment by whnr** [comment] 2019-03-19 23:00
> Do you have IPv6 enabled by any chance?

I did not disable it manually. And I do have an IPv6 address assigned.

**Comment by waterkip** [comment] 2019-03-19 23:26
I think you have the same problem as #440. I have a rather simple patch to skip IPv6 for curl (disable it actually). But I don't know if the lastpass API server do or do support IPv6 or must support it.

And I don't think I have an IPv6 box somewhere to confirm or deny that. @GPaulovics: do you have any idea?

**Comment by waterkip** [comment] 2019-03-20 09:39
Could you ckeck out my branch `gh-440-quickfix` and report back to me. 

Or could you for testing purposes disable v6 for a moment and tell me if you still experience issues?
Relevant kernel options are:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

**Comment by waterkip** [comment] 2019-03-20 14:17
Merged into master, could you check and close the issue if it has been resolved? Thanks!

**Comment by whnr** [comment] 2019-03-20 14:58
Current 1.3.1:
`lpass ls` first 2.5s, next 0.4s, subsequent 0.03s every few calls 0.4s
`lpass show --password -c GitHub` first 0.55s, next 0,45s, subsequent 0.03s, every few calls 0.4s

Git v1.3.0.41.g5531e25
`lpass ls` first 1.3s, next 1.3s, subsequent 0.03s every few calls 0.4s
`lpass show --password -c GitHub` first 0.64s, next 0,03s, subsequent 0.03s, every few calls 0.4s

=> No change

**Comment by waterkip** [comment] 2019-03-20 15:55
Hmm, I cannot seem to reproduce your problem. Oh, wait I can.

```
./build/lpass ls  0.01s user 0.01s system 1% cpu 1.238 total
# However..
./build/lpass ls --sync=no  0.01s user 0.00s system 96% cpu 0.013 total
# Reproducable with
./build/lpass ls --sync=now  0.03s user 0.02s system 14% cpu 0.338 total
```
I think it is trying to sync the data which causes some delays.
The man page says.. 

```
If auto is set, and the command displays a value, the local cache is
synchronized before the value is shown only if the local cache is more
than 5 seconds (or LPASS_AUTO_SYNC_TIME seconds, if set) old. If no is
set, the command will not interact with the server, unless there is a
current upload queue being processed.
```

**Comment by waterkip** [comment] 2019-03-20 16:22
It is the lastpass/login_check.php that is the cause of it. It takes 200ms to respond to most of my responses. And there are some exceptions:

```
$ time wget -q https://lastpass.com/login_check.php -O /dev/null
wget -q https://lastpass.com/login_check.php -O /dev/null  0.04s user 0.00s system 2% cpu 1.843 total
```

**Comment by waterkip** [comment] 2019-03-20 16:50
When you are logged in to Lastpass these checks go up to 300ms - 2 seconds. I would say this is a performance bug in the Lastpass domain, but not in the domain of the CLI client. 

I think depending on your workflow you might want to put `lpass status -q && lpass sync --background` in your `.zshrc` or `.bashrc`. When you are logged in, you will update your "blob" (it is in blob.c) in the background. Then you can increase LPASS_AUTO_SYNC_TIME to I dunno, a day or so, and you wouldn't have all this issues. Granted, it is a workaround.

**Comment by waterkip** [comment] 2019-03-20 18:58
I made a partial fix. It will hopefully decrease the time a bit, but the login_check is keeping it in the 300+ms range. Unless the tool, just like git, would require a seperate sync step, I don't see a way to increase the speed. @GPaulovics what do you think?

**Comment by GPaulovics** [comment] 2019-03-29 10:55
Well, first of all huge thank you @waterkip for investigating the issue. I'll look at why the login_check takes that long, and if it can be reduced at all. Also I'll merge the PR, hopefully it helps a little bit.

**Closed** 2019-03-29 10:55 UTC
