### ISSUE TITLE
repeatable crash in libdispatch.dylib on macOS 10.11.6

### ISSUE THREAD

**Issue by bennettsikes** [lastpass/lastpass-cli#210] opened 2016-10-17 22:00 UTC
Hello, lpass is crashing when run from ansible. Here's the crashlog:
[lpass-crashlog.txt](https://github.com/lastpass/lastpass-cli/files/534781/lpass-crashlog.txt)

I built lpass without errors using homebrew according to your instructions:

$ brew uninstall lastpass-cli
Uninstalling /usr/local/Cellar/lastpass-cli/1.0.0... (6 files, 172K)
$ brew install lastpass-cli
==> Downloading https://homebrew.bintray.com/bottles/lastpass-cli-1.0.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lastpass-cli-1.0.0.el_capitan.bottle.tar.gz
🍺 /usr/local/Cellar/lastpass-cli/1.0.0: 6 files, 171.8K

Weirdly, it's not preventing my ansible playbook from working, but it's annoying to have to dismiss the crash reporter dialog every time.

**Comment by bcopeland** [comment] 2016-10-18 18:57
This sounds like similar to #50.  I think you have libcurl compiled without using openssl but using apple security library instead; can you verify that you have libcurl-openssl?

**Comment by bennettsikes** [comment] 2016-10-19 20:50
I don't have libcurl-openssl. The crashlog shows that lpass has loaded /usr/lib/libcurl.4.dylib - I'm assuming that's the standard one installed with macOS.

If lpass requires a particular build of libcurl, can that be made a part of the homebrew formula?

**Comment by bcopeland** [comment] 2016-10-21 14:30
Yes (well, I think so, I'm not too expert on homebrew -- but we should do that if possible, and will look into it).  Also it's a bit unhelpful that the bottle is linked against that as well.

The good reason for requiring libcurl with openssl is that lpass checks the certificate chain in order to pin known keys from lastpass.com to prevent server impersonation attacks.  As far as I know, the TLS libraries shipped by Apple do not support the APIs for this.

**Comment by bcopeland** [comment] 2016-10-22 01:39
Going to close this one as a dupe of #170 -- let's hash out a solution to build issue over there.

**Closed by bcopeland** 2016-10-22 01:39 UTC

**Comment by bennettsikes** [comment] 2016-10-26 21:52
Thanks, that's great.
